[[maps.layers]]
name = "country_lines"
provider_layer = "ne.ne_110m_admin_0_boundary_lines_land"
min_zoom = 0
max_zoom = 2

[[maps.layers]]
name = "country_lines"
provider_layer = "ne.ne_50m_admin_0_boundary_lines_land"
dont_simplify = true
min_zoom = 3
max_zoom = 4

[[maps.layers]]
name = "country_lines"
provider_layer = "ne.ne_10m_admin_0_boundary_lines_land"
min_zoom = 5
max_zoom = 10

[[maps.layers]]
name = "country_lines_disputed"
provider_layer = "ne.ne_50m_admin_0_boundary_lines_disputed_areas"
min_zoom = 3
max_zoom = 4

[[maps.layers]]
name = "country_lines_disputed"
provider_layer = "ne.ne_10m_admin_0_boundary_lines_disputed_areas"
min_zoom = 5
max_zoom = 10

[[maps.layers]]
name = "country_label_points"
provider_layer = "ne.ne_10m_admin_0_label_points"
min_zoom = 3
max_zoom = 20

[[maps.layers]]
name = "country_polygons"
provider_layer = "ne.ne_110m_admin_0_countries"
min_zoom = 0
max_zoom = 2

[[maps.layers]]
name = "country_polygons"
provider_layer = "ne.ne_50m_admin_0_countries"
min_zoom = 3
max_zoom = 4

[[maps.layers]]
name = "country_polygons"
provider_layer = "ne.ne_10m_admin_0_countries"
min_zoom = 5
max_zoom = 10

[[maps.layers]]
name = "state_lines"
provider_layer = "ne.ne_110m_admin_1_states_provinces_lines"
min_zoom = 0
max_zoom = 2

[[maps.layers]]
name = "state_lines"
provider_layer = "ne.ne_50m_admin_1_states_provinces_lines"
min_zoom = 3
max_zoom = 4

[[maps.layers]]
name = "state_lines"
provider_layer = "ne.ne_10m_admin_1_states_provinces_lines"
min_zoom = 5
max_zoom = 10