# Layer configuration for amenity areas
[[providers.layers]]
name = "amenity_areas"
geometry_fieldname = "geometry"
geometry_type = "multipolygon"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    osm_id, 
    name, 
    type,
    tags->'name:ar' as name_ar, 
    tags->'name:en' as name_en, 
    tags->'name:he' as name_he, 
    tags->'name:fr' as name_fr, 
    tags->'name:hy' as name_hy 
FROM 
    osm_amenity_areas 
WHERE 
    geometry && !BBOX!
"""
