# Layer configuration for amenity points
[[providers.layers]]
name = "amenity_points"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    type,
    tags->'name:ar' as name_ar, 
    tags->'name:en' as name_en, 
    tags->'name:he' as name_he, 
    tags->'name:fr' as name_fr, 
    tags->'name:hy' as name_hy 
FROM 
    osm_amenity_points 
WHERE 
    geometry && !BBOX!
"""
