[[providers.layers]]
name = "transport_areas"
geometry_fieldname = "geometry"
geometry_type = "multipolygon"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    class, 
    type, 
    area,
    tags->'name:ar' as name_ar, 
    tags->'name:en' as name_en, 
    tags->'name:he' as name_he, 
    tags->'name:fr' as name_fr, 
    tags->'name:hy' as name_hy 
FROM 
    osm_transport_areas 
WHERE 
    geometry && !BBOX!
"""
