{{- if .Values.db.enabled -}}
{{- if .Values.db.postgresqlConfig.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-postgresql-config
  labels:
    app: {{ template "osm-seed.name" . }}
    release: {{ .Release.Name }}
data:
  postgresql.conf: |
{{ .Values.db.postgresqlConfig.values | indent 4 }}
{{- end }}
{{- end }}