{{- if and .Values.tmApi.enabled (eq .Values.serviceType "ClusterIP") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "osm-seed.fullname" . }}-ingress-tm-api
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: 5m
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    {{- if .Values.tmApi.ingressDomain }}
    - {{ .Values.tmApi.ingressDomain }}
    {{- else }}
    - tm-api.{{ .Values.domain }}
    {{- end }}
    secretName: {{ template "osm-seed.fullname" . }}-secret-tm-api
  rules:
  - host: {{ if .Values.tmApi.ingressDomain }}{{ .Values.tmApi.ingressDomain }}{{ else }}tm-api.{{ .Values.domain }}{{ end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-tasking-manager-api
            port:
              number: 80
{{- end }}