{{- if and .Values.web.enabled (eq .Values.serviceType "ClusterIP") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "osm-seed.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    {{- if .Values.web.ingressDomain }}
    - {{ .Values.web.ingressDomain }}
    {{- else }}
    - web.{{ .Values.domain }}
    {{- end }}
    - api.{{ .Values.domain }}
    - {{ .Values.domain }}
    secretName: {{ template "osm-seed.fullname" . }}-tls-secret
  rules:
  - host: {{ if .Values.web.ingressDomain }}{{ .Values.web.ingressDomain }}{{ else }}web.{{ .Values.domain }}{{ end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "osm-seed.fullname" . }}-web
            port:
              number: 80
  - host: api.{{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "osm-seed.fullname" . }}-web
            port:
              number: 80
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "osm-seed.fullname" . }}-web
            port:
              number: 80
{{- end }}
