{{- if .Values.tmDb.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tasking-manager-db
  labels:
    app: {{ template "osm-seed.name" . }}
    component: tm-db-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ template "osm-seed.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-tasking-manager-db
{{- end }}