version: '3'
services:
  # #####################################################
  # ## Taginfo section
  # #####################################################
  taginfo:
    image: osmseed-taginfo:v1
    build:
      context: ../images/taginfo
      dockerfile: Dockerfile
    ports:
      - '8000:80'
    volumes:
      - ../data/taginfo-data:/usr/src/app/data
    command: >
      /bin/bash -c "/usr/src/app/start.sh web"

    env_file:
      - ../envs/.env.taginfo
