# version: '3.8'
services:
  # ######################################################
  # ### Tiler DB
  # ######################################################
  tiler-db:
    image: osmseed-tiler-db:v1
    build:
      context: ../images/tiler-db
      dockerfile: Dockerfile
    ports:
    - "5432:5432"
    volumes:
    - ../data/tiler-db-data:/var/lib/postgresql/data
    env_file:
    - ../envs/.env.tiler-db
    restart: always
  # # ######################################################
  # # ### Tiler imposm for importing data
  # # ######################################################
  # tiler-imposm:
  #   image: osmseed-tiler-imposm:v1
  #   build:
  #     context: ../images/tiler-imposm
  #     dockerfile: Dockerfile
  #   volumes:
  #   - ../data/tiler-imposm-data:/mnt/data
  #   # - ../images/tiler-imposm:/osm
  #   command:
  #   - sh
  #   - -c
  #   - "./start.sh"
  #   env_file:
  #   - ../envs/.env.tiler-db
  #   - ../envs/.env.tiler-imposm
  #   healthcheck:
  #     test: ["CMD", "./liveness.sh"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #   restart: always
  # # ######################################################
  # # ### Tiler server
  # # ######################################################
  tiler-server:
    image: osmseed-tiler-server:v1
    # platform: linux/amd64
    build:
      context: ../images/tiler-server
      dockerfile: Dockerfile
    volumes:
      - ../images/tiler-server:/app
      - ../data/tiler-imposm-data:/mnt/data/imposm
    ports:
      - "9090:9090"
    command: "./start.sh"
    env_file:
      - ../envs/.env.tiler-db
      - ../envs/.env.tiler-server
    restart: always